### ISSUE TITLE
add custom text field plugin

### ISSUE THREAD

**Issue by gravitymaster97** [tripflex/wp-job-manager-field-editor-import#2]
<a href="https://wordpress.org/plugins/custom-field-for-wp-job-manager/">Custom Field For WP Job Manager</a> using for add text field and select field in wordpress that is good?

**Comment by tripflex** [comment]
Sorry, this plugin is specifically for my WP Job Manager Field Editor addon plugin https://plugins.smyl.es/wp-job-manager-field-editor/
